### ISSUE TITLE
A API permite transferência de valores apenas entre contas do Banco Safra?

### ISSUE THREAD

**Issue by souzalm** [banco-safra/technee#2]
O método GET mais o caminho especificado ([host]/accounts/v1/accounts/{accountId}/transfers) para a funcionalidade "Transfere valores entre contas" apenas permite a transferência entre contas do Banco Safra? Ou o PIX já está sendo considerado para essas transferências? E seria permitido a transferência entre contas do Banco Safra e contas de outros bancos?

**Comment by oliveira-michel** [comment]
Olá, @souzalm , os cenários mockados contemplam 2 transferências entre contas Safra. Os cenários mockados disponíveis estão descritos neste documento:

https://github.com/banco-safra/technee/blob/master/documentacao-tecnica/APIs.pdf

Não consideramos PIX. Não há contas de outros bancos nos cenários.

**Comment by oliveira-michel** [comment]
Estou fechando este Issue. Caso tenha mais dúvidas, fique à vontade para perguntar. Boa sorte no desafio.
